### ISSUE TITLE
Add a way to express a selector which only walks or matches HAMTs

### ISSUE THREAD

**Issue by magik6k** [ipfs/go-unixfsnode#37]
Right now it's not possible to write a selector which will only match/walk all blocks of a hamt without loading child nodes (which may mean loading 1000x more data just to list entries in a directory)

**Comment by willscott** [comment]
the 'easiest' way to do this will be to add an option for a mode of the ADL that fully loads a sharded directory on node loading, and then register this under a variant name (e.g. `unixfs-nonlazy`)
